# Generated by Django 3.2.5 on 2021-11-06 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dept', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpVo',
            fields=[
                ('emp_no', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.TextField()),
                ('job', models.TextField()),
                ('mgr', models.IntegerField()),
                ('hire_date', models.DateField()),
                ('sal', models.IntegerField()),
                ('comm', models.IntegerField()),
                ('dept_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dept.deptvo')),
            ],
            options={
                'db_table': 'emp',
                'managed': True,
            },
        ),
    ]
