# Generated by Django 3.2.5 on 2021-11-16 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='log_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 16, 18, 16, 24, 221885)),
        ),
    ]
